pr:
  branches:
    include:
      - 'main'
  
name: 'ci_pipeline'
jobs:
- job: 'ci_pipeline_job'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  
  - script: |      
      pylint --output-format=pylint_junit.JUnitReporter --disable=C0114,C0115,C0116,E0110,E1101,E1123,R0801 src/my_custom_package/ > linting-testresults.xml
    displayName: 'Run code quality tests (Pylint)'
