trigger: none

schedules:
  - cron: "0 13 * * 0"
    displayName: "Weekly Sunday deployment pipeline run"
    branches:
      include:
      - master
    always: true

name: 'deployment_pipeline'
jobs:
  - job: 'deployment_pipeline_job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: KeyVault
      - group: ProductionEnvVars
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
    
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install requirements'
    
      - script: |
          python src/my_custom_package/deploy_aml_model.py
        displayName: 'Deploy AML Model to ACI Web Service'
        env:
          TENANT_ID: $(TenantID)
          SPN_ID: $(SpnID)
          SPN_PASSWORD: $(SpnPassword)
          AML_WORKSPACE_NAME: $(AmlWorkspaceName)
          RESOURCE_GROUP: $(ResourceGroup)
          SUBSCRIPTION_ID: $(SubscriptionID)
